# Generated by Django 4.1.3 on 2022-11-18 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_combustivel', models.CharField(max_length=100)),
                ('qtdd_estoque', models.IntegerField()),
                ('capacidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompraCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCompra', models.DateField()),
                ('qtdd_litros', models.IntegerField()),
                ('preco_litro', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('descricao', models.CharField(max_length=100)),
                ('capacidade_tanque', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datAbastecimento', models.DateField()),
                ('qtd_litro', models.IntegerField()),
                ('km_odometro', models.IntegerField()),
                ('nomeFuncionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pump.funcionario')),
            ],
        ),
    ]
