# Generated by Django 4.1.1 on 2022-11-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump', '0003_abastecimento_placa_abastecimento_tipogas'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='a_pagar',
            field=models.FloatField(null=True),
        ),
    ]
