# Generated by Django 4.0.3 on 2022-11-21 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pump', '0004_abastecimento_a_pagar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abastecimento',
            name='a_pagar',
        ),
    ]
